version: '2'

services:
  h5ai:
    image: bixidock/h5ai
    volumes:
      - /data:/var/www
  aria2:
    image: wahyd4/aria2-ariang:caddy
    ports:
      - "8000:80"
      - "443:443"
      - "6800:6800"
    volumes_from:
      - h5ai
    environment:
      - DOMAIN=localhost:80
      - SSL=true
      - RPC_SECRET=Hello
      - ARIA2_USER=admin
      - ARIA2_PWD=password
      - ENABLE_AUTH=true
    links:
      - h5ai:file-manager


