version: '2'

services:
  nextcloud:
    image: wonderfall/nextcloud
    volumes:
      - /data/nextcloud:/data
      - /data:/user-files
  aria2:
    image: wahyd4/aria2-ariang:nextcloud
    ports:
      - "8000:80"
      - "6800:6800"
      - "443:443"
    volumes_from:
      - nextcloud
    environment:
      - DOMAIN=localhost:80
      # - SSL=true
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    links:
      - nextcloud:file-manager


